Backend/WebsiteBanQuanAo/Controllers/HomeController.cs
using NXHOANG.ApplicationCore.Interface.Service;
using NXHOANG.DoAnTotNghiep.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NXHOANG.ApplicationCore.EtensionMethod;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using NXHOANG.ApplicationCore.Entity;
using NXHOANG.ApplicationCore.ViewModel;
using NXHOANG.ApplicationCore.Enum;
using NXHOANG.ApplicationCore.Common;
using Microsoft.AspNetCore.Http;

namespace NXHOANG.DoAnTotNghiep.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUserService _userService;
        private readonly IProductService _productService;


        public HomeController(ILogger<HomeController> logger, IUserService userService, IProductService productService)
        {
            _logger = logger;
            _userService = userService;
            _productService = productService;
        }

        public IActionResult Index()
        {
            HomeViewModel homeViewModel = new HomeViewModel();

            homeViewModel = _productService.GetProducts().Result;

            return View(homeViewModel);
        }

        /// <summary>
        /// View sau khi tìm kiếm
        /// </summary>
        /// <param name="keyword">Text Search</param>
        /// <param name="page">Trang hiện tại</param>
        /// <returns></returns>
        /// NXHOANG
        public IActionResult Search(string keyword, int page = 1)
        {
            int pageSize = ConfigHelper.pageSize;

            if (HttpContext.Session.GetString(CommonConstant.SessionSearch) == null || HttpContext.Session.GetString(CommonConstant.SessionSearch) == "")
            {
                HttpContext.Session.SetString(CommonConstant.SessionSearch, keyword);
            }

            var keySearch = (keyword == null ? HttpContext.Session.GetString(CommonConstant.SessionSearch) : keyword);

            var productCategoryViewModel =  _productService.getAllProductSearch(keySearch, page, pageSize).Result;

            int totalPage = (int)Math.Ceiling((double)productCategoryViewModel.TotalProducts / pageSize);

            ViewBag.keyword = keyword;

            var paginationSet = new PaginationSet
            {
                Item = productCategoryViewModel,    
                MaxPage = ConfigHelper.MaxPage,
                Page = page,
                TotalCount = productCategoryViewModel.TotalProducts,
                TotalPages = totalPage
            };

            return View(paginationSet);
        }


        /// <summary>
        /// View đăng nhập
        /// </summary>
        /// <returns></returns>
        /// NXHOANG 24/07/2022
        public IActionResult Login()
        {
            return View();
        }


        /// <summary>
        /// Đăng ký
        /// </summary>
        /// <returns></returns>
        /// NXHOANG 24/07/2022
        public IActionResult Register()
        {
            return View();  
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Backend/WebsiteBanQuanAo/ViewComponents/SliderViewComponent.cs
using NXHOANG.ApplicationCore.Entity;
using NXHOANG.ApplicationCore.Interface.Service;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NXHOANG.DoAnTotNghiep.ViewComponents
{
    public class SliderViewComponent : ViewComponent
    {
        #region Declare
        private readonly ISlideService _slideService;
        #endregion

        #region Constructor
        public SliderViewComponent(ISlideService slideService)
        {
            _slideService = slideService;
        }

        #endregion


        public IViewComponentResult Invoke()
        {
            var slides = _slideService.GetEntities().Result as List<Slide>;

            return View(slides);
        }
    }
}

Backend/WebsiteBanQuanAo/Views/Home/Index.cshtml
@model NXHOANG.ApplicationCore.ViewModel.HomeViewModel


@{
    ViewData["Title"] = "Home Page";
}

<link rel="stylesheet" href="~/css/CustomCss/ProductSection.css" />

<!--Slide -->
<section id="home-section" class="hero">

    @await Component.InvokeAsync("Slider");

</section>

@if (Model.TableLatests.Count > 0)
{
    <section class="ftco-section product-section">
        <div class="container">
            <div class="row justify-content-center mb-3 pb-3">
                <div class="col-md-12 heading-section text-center ftco-animate">

                    <span class="subheading">Bàn Ghế Mới Nhất</span>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">

                @{

                    foreach (var item in Model.TableLatests)
                    {
                        var urlImage = "";

                        // Bàn Ghế
                        urlImage = "/images/ImageProduct/BanGhe/" + item.Image;

                        var urlProductDetail = "/" + "san-pham-chi-tiet" + "/" + item.ProductId + ".html";

                        <div class="col-md-6 col-lg-3 ftco-animate">
                            <div class="product">
                                <a href="#" class="img-prod">
                                    <img class="img-fluid" src=@urlImage alt="Colorlib Template">
                                    <span class="status">30%</span>
                                    <div class="overlay"></div>
                                </a>
                                <div class="text py-3 pb-4 px-3 text-center">
                                    <h3>
                                        <a href="#" title="@item.ProductName">
                                            <div class="product-name-text">@item.ProductName</div>
                                        </a>
                                    </h3>
                                    <div class="d-flex">
                                        <div class="pricing">
                                            <p class="price">
                                                @if (item.PromotionPrice != null && item.PromotionPrice != 0)
                                                {
                                                    <span class="mr-2 price-dc">@((Math.Round((decimal)item.Price, 0, MidpointRounding.AwayFromZero)).ToString("N0").Replace(",", ".")) Vnđ</span><span class="price-sale">@((Math.Round((decimal)item.PromotionPrice, 0, MidpointRounding.AwayFromZero)).ToString("N0").Replace(",", ".")) Vnđ</span>
                                                }
                                                else
                                                {
                                                    <span class="mr-2 price-sale">@((Math.Round((decimal)item.Price, 0, MidpointRounding.AwayFromZero)).ToString("N0").Replace(",", ".")) Vnđ</span>
                                                }
                                            </p>
                                        </div>
                                    </div>
                                    <div class="bottom-area d-flex px-3">
                                        <div class="m-auto d-flex">
                                            <a href="@urlProductDetail" class="add-to-cart d-flex justify-content-center align-items-center text-center">
                                                <span>
                                                    <i class="fa fa-bars" aria-hidden="true"></i>
                                                </span>
                                            </a>
                                            <a class="buy-now d-flex justify-content-center align-items-center mx-1 btnAddToCart" data-id="@item.ProductId">
                                                <span>
                                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                                </span>
                                            </a>
                                            <a href="#" class="heart d-flex justify-content-center align-items-center ">
                                                <span>
                                                    <i class="fa fa-heart" aria-hidden="true"></i>
                                                </span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                }

            </div>
        </div>
    </section>

}


@if (Model.CabinetLatests.Count > 0)
{
    <section class="ftco-section product-section">
        <div class="container">
            <div class="row justify-content-center mb-3 pb-3">
                <div class="col-md-12 heading-section text-center ftco-animate">
                    @*<span class="subheading">Featured Products</span>
                        <h2 class="mb-4">Our Products</h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>*@

                    @*<h2 class="mb-4">Sản Phẩm Mới Nhất</h2>*@
                    <span class="subheading">Tủ Mới Nhất</span>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">

                @{

                    foreach (var item in Model.CabinetLatests)
                    {
                        var urlImage = "";

                        // Tủ
                        urlImage = "/images/ImageProduct/Tu/" + item.Image;

                        var urlProductDetail = "/" + "san-pham-chi-tiet" + "/" + item.ProductId + ".html";

                        <div class="col-md-6 col-lg-3 ftco-animate">
                            <div class="product">
                                <a href="#" class="img-prod">
                                    <img class="img-fluid" src=@urlImage alt="Colorlib Template">
                                    <span class="status">30%</span>
                                    <div class="overlay"></div>
                                </a>
                                <div class="text py-3 pb-4 px-3 text-center">
                                    <h3><a href="#">@item.ProductName</a></h3>
                                    <div class="d-flex">
                                        <div class="pricing">
                                            <p class="price">
                                                @if (item.PromotionPrice != null && item.PromotionPrice != 0)
                                                {
                                                    <span class="mr-2 price-dc">@((Math.Round((decimal)item.Price, 0, MidpointRounding.AwayFromZero)).ToString("N0").Replace(",", ".")) Vnđ</span><span class="price-sale">@((Math.Round((decimal)item.PromotionPrice, 0, MidpointRounding.AwayFromZero)).ToString("N0").Replace(",", ".")) Vnđ</span>
                                                }
                                                else
                                                {
                                                    <span class="mr-2 price-sale">@((Math.Round((decimal)item.Price, 0, MidpointRounding.AwayFromZero)).ToString("N0").Replace(",", ".")) Vnđ</span>
                                                }
                                            </p>
                                        </div>
                                    </div>
                                    <div class="bottom-area d-flex px-3">
                                        <div class="m-auto d-flex">
                                            <a href="@urlProductDetail" class="add-to-cart d-flex justify-content-center align-items-center text-center">
                                                <span>
                                                    <i class="fa fa-bars" aria-hidden="true"></i>
                                                </span>
                                            </a>
                                            <a href="#" class="buy-now d-flex justify-content-center align-items-center mx-1 btnAddToCart" data-id="@item.ProductId">
                                                <span>
                                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                                </span>
                                            </a>
                                            <a href="#" class="heart d-flex justify-content-center align-items-center ">
                                                <span>
                                                    <i class="fa fa-heart" aria-hidden="true"></i>
                                                </span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                }

            </div>
        </div>
    </section>

}

@if (Model.BedLatests.Count > 0)
{
    <section class="ftco-section product-section">
        <div class="container">
            <div class="row justify-content-center mb-3 pb-3">
                <div class="col-md-12 heading-section text-center ftco-animate">
                    <span class="subheading">Giường Mới Nhất</span>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">

                @{

                    foreach (var item in Model.BedLatests)
                    {
                        var urlImage = "";

                        // Giường
                        urlImage = "/images/ImageProduct/Giuong/" + item.Image;

                        var urlProductDetail = "/" + "san-pham-chi-tiet" + "/" + item.ProductId + ".html";

                        <div class="col-md-6 col-lg-3 ftco-animate">
                            <div class="product">
                                <a href="#" class="img-prod">
                                    <img class="img-fluid" src=@urlImage alt="Colorlib Template">
                                    <span class="status">30%</span>
                                    <div class="overlay"></div>
                                </a>
                                <div class="text py-3 pb-4 px-3 text-center">
                                    <h3><a href="#">@item.ProductName</a></h3>
                                    <div class="d-flex">
                                        <div class="pricing">
                                            <p class="price">
                                                @if (item.PromotionPrice != null && item.PromotionPrice != 0)
                                                {
                                                    <span class="mr-2 price-dc">@((Math.Round((decimal)item.Price, 0, MidpointRounding.AwayFromZero)).ToString("N0").Replace(",", ".")) Vnđ</span><span class="price-sale">@((Math.Round((decimal)item.PromotionPrice, 0, MidpointRounding.AwayFromZero)).ToString("N0").Replace(",", ".")) Vnđ</span>
                                                }
                                                else
                                                {
                                                    <span class="mr-2 price-sale">@((Math.Round((decimal)item.Price, 0, MidpointRounding.AwayFromZero)).ToString("N0").Replace(",", ".")) Vnđ</span>
                                                }
                                            </p>
                                        </div>
                                    </div>
                                    <div class="bottom-area d-flex px-3">
                                        <div class="m-auto d-flex">
                                            <a href="@urlProductDetail" class="add-to-cart d-flex justify-content-center align-items-center text-center">
                                                <span>
                                                    <i class="fa fa-bars" aria-hidden="true"></i>
                                                </span>
                                            </a>
                                            <a href="#" class="buy-now d-flex justify-content-center align-items-center mx-1 btnAddToCart" data-id="@item.ProductId">
                                                <span>
                                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                                </span>
                                            </a>
                                            <a href="#" class="heart d-flex justify-content-center align-items-center ">
                                                <span>
                                                    <i class="fa fa-heart" aria-hidden="true"></i>
                                                </span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                }

            </div>
        </div>
    </section>

}

Backend/WebsiteBanQuanAo/Views/Home/Login.cshtml
@{
    ViewData["Title"] = "Login";
}


<link rel="stylesheet" href="/css/CustomCss/login.css" />

<section class="ftco-section ftco-cart section-login">
    <div class="container">
        <div class="row row-margin-top">
            <div class="col-6">
                <div>
                    <div class="reservation_top">
                        <div class="contact_right">
                            <h4 class="text-center">Đăng nhập</h4>
                            <div class="contact-form">
                                <form method="post" id="frmPayment">

                                    <div class="form-group">
                                        <input type="text" class="textbox form-control" id="txtUserEmail" name="name" placeholder="Email (*)">
                                        <span class="error-validate validate-email"></span>
                                    </div>

                                    <div class="form-group">
                                        <input type="password" class="textbox form-control" id="txtPassWord" name="passWord" placeholder="Mật khẩu (*)">
                                        <span class="error-validate validate-password"></span>
                                    </div>

                                    <div class="form-group">
                                        <button type="button" class="btn btn-confirm" id="btnLogin">
                                            <i class="fa fa-sign-in" aria-hidden="true"></i>
                                            <span>Đăng nhập</span>
                                        </button>
                                    </div>

                                    <div class="clearfix"> </div>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div>
                    <div class="reservation_top">
                        <div class="contact_right">
                            <h4 class="text-center">Đăng nhập với mạng xã hội</h4>
                            <div class="contact-form">
                                <div class="social-login text-center">
                                    <a href="#" class="facebook btn btn-block" id="facebook">
                                        <span class="mr-3">
                                            <i class="fa fa-facebook" aria-hidden="true"></i>
                                        </span>
                                    </a>
                                    <a href="#" class="google btn btn-block" id="google">
                                        <span class="mr-3">
                                            <i class="fa fa-google" aria-hidden="true"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-6">
                <div class="login-left">
                    <h4>Chưa có tài khoản</h4>
                    <p>Nếu bạn chưa có tài khoản vui lòng đăng ký tại link dưới đây:</p>
                    <a class="acount-btn" href="/dang-ky.html">Đăng ký thành viên</a>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>

    </div>
</section>


<style>

    #facebook {
        width: 100%;
        color: white;
        background-color: #4267B2;
        height: 40px;
        line-height: 26px;
        font-size: 19px;
        border-radius: 6px;
    }

    #google {
        border-radius: 5px;
        background: #db4437;
        color: white;
        width: 100%;
        line-height: 26px;
        height: 40px;
        font-size: 21px;
    }

</style>

Backend/WebsiteBanQuanAo/Views/Home/Register.cshtml
@{
    ViewData["Title"] = "Register";
}


<link rel="stylesheet" href="/css/CustomCss/register.css" />

<section class="ftco-section ftco-cart section-login">
    <div class="container">
        <div class="row row-margin-top">    
            <div class="col-12">
                <div>
                    <div class="reservation_top">
                        <div class="contact_right">
                            <h4 class="text-center">Đăng ký tài khoản</h4>
                            <div class="contact-form">
                                <form method="post" id="frmPayment">

                                    <div class="form-group">
                                        <input type="text" class="textbox form-control" id="txtUserName" name="UserName" placeholder="Họ tên (*)">
                                        <span class="error-validate validate-user-name"></span>
                                    </div>

                                    <div class="form-group">
                                        <input type="text" class="textbox form-control" id="txtUserEmail" name="Email" placeholder="Email (*)">
                                        <span class="error-validate validate-user-email"></span>
                                    </div>

                                    <div class="form-group">
                                        <input type="text" class="textbox form-control" id="txtUserPhone" name="UserPhone" placeholder="Số điện thoại (*)">
                                        <span class="error-validate validate-user-Phone"></span>
                                    </div>

                                    <div class="form-group">
                                        <input type="text" class="textbox form-control" id="txtUserAddress" name="UserAddress" placeholder="Địa chỉ (*)">
                                        <span class="error-validate validate-user-address"></span>
                                    </div>

                                    <div class="form-group">
                                        <input type="password" class="textbox form-control" id="txtPassWord" name="passWord" placeholder="Mật khẩu (*)">
                                        <span class="error-validate validate-user-password"></span>
                                    </div>

                                    <div class="form-group">
                                        <input type="password" class="textbox form-control" id="txtPassWordAgain" name="passWord" placeholder="Nhập lại mật khẩu (*)">
                                        <span class="error-validate validate-user-password-again"></span>
                                    </div>

                                    <div class="form-group">
                                        <button type="button" class="btn btn-confirm" id="btnRegister">
                                            <i class="fa fa-user" aria-hidden="true"></i>
                                            <span>Đăng ký</span>
                                        </button>
                                    </div>

                                    <div class="clearfix"> </div>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>