Backend/WebsiteBanQuanAo/Controllers/ProductCategoryController.cs
using NXHOANG.ApplicationCore.Common;
using NXHOANG.ApplicationCore.Interface.Service;
using NXHOANG.ApplicationCore.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NXHOANG.DoAnTotNghiep.Controllers
{
    public class ProductCategoryController : Controller
    {

        #region Declare
        private readonly IProductCategoryService _productCategoryService;
        #endregion

        #region Constructor
        public ProductCategoryController(IProductCategoryService productCategoryService)
        {
            _productCategoryService = productCategoryService;
        }

        #endregion
        /// <summary>
        /// View Danh Mục Sản Phẩm
        /// </summary>
        /// <param name="ProductCategoryId">Id danh mục</param>
        /// <param name="page">Trang hiện tại</param>
        /// <returns></returns>
        /// NXHOANG
        public IActionResult Index(Guid? ProductCategoryId, int page = 1)
        {
            int pageSize = ConfigHelper.pageSize;

            var productCategoryViewModel = _productCategoryService.getAllProductCategory(ProductCategoryId, page, pageSize).Result;

            int totalPage = (int)Math.Ceiling((double)productCategoryViewModel.TotalProducts / pageSize);

            var paginationSet = new PaginationSet
            {
                Item = productCategoryViewModel,
                MaxPage = ConfigHelper.MaxPage,
                Page = page,
                TotalCount = productCategoryViewModel.TotalProducts,
                TotalPages = totalPage
            };

            return View(paginationSet);
        }

        


    }
}

Backend/WebsiteBanQuanAo/ViewComponents/SliderOptionViewComponent.cs
using NXHOANG.ApplicationCore.Entity;
using NXHOANG.ApplicationCore.Interface.Service;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NXHOANG.DoAnTotNghiep.ViewComponents
{
    public class SliderOptionViewComponent : ViewComponent
    {
        #region Declare
        private readonly ISlideService _slideService;
        #endregion

        #region Constructor
        public SliderOptionViewComponent(ISlideService slideService)
        {
            _slideService = slideService;
        }

        #endregion

        public IViewComponentResult Invoke()
        {
            var slides = _slideService.GetEntities().Result as List<Slide>;
            return View(slides);
        }
    }
}

Backend/WebsiteBanQuanAo/Views/ProductCategory/Index.cshtml
@model NXHOANG.ApplicationCore.ViewModel.PaginationSet;

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="/css/CustomCss/ProductCategorySection.css" />


@*@await Component.InvokeAsync("SliderOption");*@

<!--Slide -->
<section id="home-section" class="hero">

    @await Component.InvokeAsync("SliderOption");

</section>


<section class="ftco-section product-category-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10 mb-5 text-center">
                <ul class="product-category">

                    @foreach (var item in Model.Item.productCategories)
                    {
                        var urlCategory = "danh-muc-" + item.ProductCategoryLink + "/" + item.ProductCategoryId;
                       @* if (item.ProductCategoryId == Model.Item.productCategoryActive.ProductCategoryId)
                        {
                            <li><a href="/@urlCategory" class="active">@item.ProductCategoryName</a></li>
                        }
                        else
                        {*@
                            <li><a href="/@urlCategory">@item.ProductCategoryName</a></li>
                        //}

                    }

                </ul>
            </div>
        </div>
        <div class="row">

            @{

                foreach (var item in Model.Item.products)
                {
                    var urlImage = "";

                    if (item.TypeProduct == 1)
                    {
                        // Bàn Ghế
                        urlImage = "/images/ImageProduct/BanGhe/" + item.Image;
                    }
                    else if (item.TypeProduct == 2)
                    {
                        // Tủ
                        urlImage = "/images/ImageProduct/Tu/" + item.Image;
                    }
                    else if (item.TypeProduct == 3)
                    {
                        //Giường
                        urlImage = "/images/ImageProduct/Giuong/" + item.Image;
                    }

                    var urlProductDetail = "/" + "san-pham-chi-tiet" + "/" + item.ProductId + ".html";

                    <div class="col-md-6 col-lg-3 ftco-animate">
                        <div class="product">
                            <a href="#" class="img-prod">
                                <img class="img-fluid" src=@urlImage alt="Colorlib Template">
                                <span class="status">30%</span>
                                <div class="overlay"></div>
                            </a>
                            <div class="text py-3 pb-4 px-3 text-center">
                                <h3>
                                    <a href="#" title="@item.ProductName">
                                        <div class="product-name-text">@item.ProductName</div>
                                    </a>
                                </h3>
                                <div class="d-flex">
                                    <div class="pricing">
                                        <p class="price">
                                            @if (item.PromotionPrice != null && item.PromotionPrice != 0)
                                            {
                                                <span class="mr-2 price-dc">@((Math.Round((decimal)item.Price, 0, MidpointRounding.AwayFromZero)).ToString("N0").Replace(",", ".")) Vnđ</span><span class="price-sale">@((Math.Round((decimal)item.PromotionPrice, 0, MidpointRounding.AwayFromZero)).ToString("N0").Replace(",", ".")) Vnđ</span>
                                            }
                                            else
                                            {
                                                <span class="mr-2 price-sale">@((Math.Round((decimal)item.Price, 0, MidpointRounding.AwayFromZero)).ToString("N0").Replace(",", ".")) Vnđ</span>
                                            }
                                        </p>
                                    </div>
                                </div>
                                <div class="bottom-area d-flex px-3">
                                    <div class="m-auto d-flex">
                                        <a href="@urlProductDetail" class="add-to-cart d-flex justify-content-center align-items-center text-center">
                                            <span>
                                                <i class="fa fa-bars" aria-hidden="true"></i>
                                            </span>
                                        </a>
                                        <a href="#" class="buy-now d-flex justify-content-center align-items-center mx-1 btnAddToCart" data-id="@item.ProductId">
                                            <span>
                                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                            </span>
                                        </a>
                                        <a href="#" class="heart d-flex justify-content-center align-items-center ">
                                            <span>
                                                <i class="fa fa-heart" aria-hidden="true"></i>
                                            </span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }

        </div>
        <div class="row mt-5">
            <div class="col text-center">
                <div class="block-27">
                    <ul>
                        @if (Model.TotalPages > 1)
                        {
                            <li>
                                <a href="?page=@(Model.Page-1)">
                                    &lt;
                                </a>
                            </li>

                            var startPageIndex = Math.Max(1, Model.Page - Model.MaxPage / 2);
                            var endPageIndex = Math.Min(Model.TotalPages, Model.Page + Model.MaxPage / 2);

                            for (int i = startPageIndex; i <= endPageIndex; i++)
                            {
                                if (Model.Page == i)
                                {
                                    <li class="active">
                                        <span>
                                            <a href="?page=@i" title="trang @i">@i</a>
                                        </span>
                                    </li>
                                }
                                else
                                {
                                    <li>
                                        <a href="?page=@i" title="Trang @i">@i</a>
                                    </li>
                                }
                            }

                            <li>
                                <a href="?page=@(Model.Page+1)">
                                    &gt;
                                </a>
                            </li>

                        }
                        @*<li><a href="#">&lt;</a></li>
                        <li class="active"><span>1</span></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">&gt;</a></li>*@
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>