Backend/WebsiteBanQuanAo/ViewComponents/FooterViewComponent.cs
using NXHOANG.ApplicationCore.Entity;
using NXHOANG.ApplicationCore.Interface.Repository;
using NXHOANG.ApplicationCore.Interface.Service;
using NXHOANG.ApplicationCore.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace NXHOANG.DoAnTotNghiep.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        #region Declare
        private readonly IFooterProductService _footerProductService;
        #endregion

        #region Constructor
        public FooterViewComponent(IFooterProductService footerProductService)
        {
            _footerProductService = footerProductService;
        }
        #endregion

        public IViewComponentResult Invoke()
        {

            FooterViewModel footerViewModel = new FooterViewModel();

            footerViewModel = _footerProductService.GetFooterProducts().Result;

            return View(footerViewModel);
        }
    }
}

Backend/WebsiteBanQuanAo/ViewComponents/HeaderViewComponent.cs
using NXHOANG.ApplicationCore.Common;
using NXHOANG.ApplicationCore.Entity;
using NXHOANG.ApplicationCore.Interface.Service;
using NXHOANG.ApplicationCore.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NXHOANG.DoAnTotNghiep.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        #region Declare
        private readonly IMenuHeaderService _menuHeaderService;
        private readonly IProductCategoryService _productCategoryService;
        #endregion

        #region Constructor
        public HeaderViewComponent(IMenuHeaderService menuHeaderService, IProductCategoryService productCategoryService)
        {
            _menuHeaderService = menuHeaderService;
            _productCategoryService = productCategoryService;
        }
        #endregion

        public IViewComponentResult Invoke()
        {

            MenuHeaderViewModel menuHeader = new MenuHeaderViewModel();

            var menuHeaders = _menuHeaderService.GetEntities().Result as List<MenuHeader>;

            var productCategory = _productCategoryService.GetEntities().Result as List<ProductCategory>;

            menuHeader.ListMenuHeader = menuHeaders;
            menuHeader.ListProductCategory = productCategory;

            var cartJson = HttpContext.Session.GetString(CommonConstant.SessionCart);

            var cartParseJson = new List<ShoppingCartViewModel>();

            if (cartJson != null)
            {
                cartParseJson = JsonConvert.DeserializeObject<List<ShoppingCartViewModel>>(cartJson);
            }

            menuHeader.CountCart = cartParseJson.Sum(x => x.Quantity);

            // Truyền session vào viewBag

            var userJson = HttpContext.Session.GetString(CommonConstant.UserLogin);

            var isLogin = false;

            if (userJson != null)
            {
                var userLogin = JsonConvert.DeserializeObject<User>(userJson);
                ViewBag.userLogin = userLogin;
                isLogin = true;
            }

            ViewBag.isLogin = isLogin;

            return View(menuHeader);
        }
    }
}

Backend/WebsiteBanQuanAo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>NX Hoàng</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/css/animate.css">

    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">

    <link rel="stylesheet" href="~/css/aos.css">

    <link rel="stylesheet" href="~/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/css/jquery.timepicker.css">



    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/icomoon.css">

    <link rel="stylesheet" href="~/css/ionicons.min.css">
    <link rel="stylesheet" href="~/css/style.css">

    <link href="~/js/Toastr/toastr.css" rel="stylesheet" />

</head>
<body class="goto-here">
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">

        @await Component.InvokeAsync("Header")

    </nav>


    <!-- Body -->

    @RenderBody()

    <footer class="ftco-footer ftco-section">

        @await Component.InvokeAsync("Footer")

    </footer>

    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>


    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/Mustache/node_modules/mustache/mustache.js"></script>
    <script src="~/js/JsCustom/ShoppingCart.js"></script>
    <script src="~/js/JsCustom/ProductDetail.js"></script>
    <script src="/js/JsCustom/login.js"></script>
    <script src="/js/JsCustom/register.js"></script>
    <script src="~/js/Toastr/toastr.min.js"></script>
    <script src="~/js/Libs/NumeralJs/min/numeral.min.js"></script>
    <script src="~/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.stellar.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/aos.js"></script>
    <script src="~/js/jquery.animateNumber.min.js"></script>
    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/js/google-map.js"></script>
    <script src="~/js/main.js"></script>

</body>
</html>